---
apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  minReadySeconds: 25
  replicas: 2
  selector: 
    matchLabels:
      app: spc
  template:
    metadata: 
      labels: 
        app: spc
        env: dev
    spec:
      containers:
        -name: spc
        image: shaikkhajaibrahim/spcjan2024:1.0
        ports:
          - containers: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
spec: 
  type: NodePort
  selector: spc
  ports: 
    - port: 8080
      targetPort: 8080
      protocol: TCP



                           

