---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: fe-rs
  labels:
    env: app
    topic: rs
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels: 
      app: fe
  template:
    metadata:
     labels:
       app: fe
       topic: pod
    spec:
      containers:
        - name: fe-cont
          image: nginx
          ports:
              - containerPort: 80
    resources:
          limits: 
          cpu: "250m"
          memory: "128Mi" 
    livenessProbe: 
      failureThreshold: 1
      successThreshold: 1
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
       path: /
       port: 80
    readinessProbe: 
       failureThreshold: 1
       successThreshold: 2
       initialDelaySeconds: 5
       periodSeconds: 10
       httpGet:
       path: /
       port: 80         
---                 
            