---
apiVersion: v1
kind: Pod
metadata:
  name: exp1
  labels:
    app: mysql
spec:
  containers:
    - name: excercise1
      image: mysql:8.0-debian
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: admin123
       - name: MYSQL_DATABASE
         value: mysql
       - name: MYSQL_USER
         value: ltdevops
       - name: MYSQL_PASSWORD
         value: admin123
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
      ports:
        - containerPort: 3306     
---        