---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spc
  labels:
    env: dev
    topic: Replicaset
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels: 
      app: spc
  template:
    metadata:
        labels:
          app: spc
          env: dev
          topic: pod
    spec:
        containers:
         - name: spc
           image: spc:1.0
        ports:
          - containerPort: 80
    resources:
          limits: 
          cpu: "250m"
          memory: "128Mi" 
---                   